language: python
python:
  - "2.7"
  - "2.6"
install:
  - pip install -e . -r requirements-testing.txt $DJANGO_VERSION
script:
  - django-admin.py test --settings=dumper.test.settings dumper
after_success:
  - coveralls
env:
  matrix:
    - DJANGO_VERSION="https://www.djangoproject.com/download/1.6a1/tarball/"
    - DJANGO_VERSION="django>=1.5,<1.6"
    - DJANGO_VERSION="django>=1.4,<1.5"
    - DJANGO_VERSION="django>=1.3,<1.4"
matrix:
  allow_failures:
    - env: DJANGO_VERSION="https://www.djangoproject.com/download/1.6a1/tarball/"
