language: python
sudo: false
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
install:
  - pip install -e . -r requirements-testing.txt $DJANGO_VERSION
script:
  - django-admin.py test --settings=test.settings
env:
  matrix:
    - DJANGO_VERSION="django==1.8.*"
    - DJANGO_VERSION="django==1.7.*"
    - DJANGO_VERSION="django==1.6.*"
    - DJANGO_VERSION="django==1.5.*"
    - DJANGO_VERSION="django==1.4.*"
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION="django==1.6.*"
    - python: "2.6"
      env: DJANGO_VERSION="django==1.7.*"
    - python: "2.6"
      env: DJANGO_VERSION="django==1.8.*"

    - python: "3.2"
      env: DJANGO_VERSION="django==1.3.*"
    - python: "3.2"
      env: DJANGO_VERSION="django==1.4.*"
    - python: "3.3"
      env: DJANGO_VERSION="django==1.3.*"
    - python: "3.3"
      env: DJANGO_VERSION="django==1.4.*"
    - python: "3.4"
      env: DJANGO_VERSION="django==1.3.*"
    - python: "3.4"
      env: DJANGO_VERSION="django==1.4.*"
    - python: "3.5"
      env: DJANGO_VERSION="django==1.3.*"
    - python: "3.5"
      env: DJANGO_VERSION="django==1.4.*"
    - python: "3.5"
      env: DJANGO_VERSION="django==1.5.*"
    - python: "3.5"
      env: DJANGO_VERSION="django==1.6.*"
    - python: "3.5"
      env: DJANGO_VERSION="django==1.7.*"
